# Generated by Django 3.1.2 on 2021-01-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0003_auto_20210113_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zulieferer',
            options={'verbose_name_plural': 'Zulieferer'},
        ),
    ]
