# Generated by Django 3.1.2 on 2021-01-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0004_auto_20210113_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='zulieferer',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
