# Generated by Django 3.1.2 on 2021-01-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0009_auto_20210114_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorrat',
            name='zutatnummer',
            field=models.OneToOneField(blank=True, db_column='zutatnummer', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bestellung.zutat'),
        ),
    ]
