# Generated by Django 3.1.2 on 2021-01-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0010_auto_20210114_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={},
        ),
    ]
