# Generated by Django 3.1.2 on 2021-01-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0016_auto_20210117_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutat',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
