# Generated by Django 3.1.5 on 2021-01-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0018_bestellung_kundenmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='kundenmail',
            field=models.TextField(),
        ),
    ]
