# Generated by Django 3.1.5 on 2021-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0020_auto_20210127_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='kundenmail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
