# Generated by Django 3.1.5 on 2021-01-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0023_auto_20210129_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='groesse',
            field=models.CharField(blank=True, choices=[('klein', 'klein'), ('normal', 'normal'), ('gross', 'groß')], max_length=6, null=True),
        ),
    ]
